const path = (name) => `/static/icons/images/${name}.png`;
const ImagesConfig = {
  sharedBack: path('ic_shared'),
  newGift: path('ic_newGift'),
  giftCard: path('ic_giftCard'),
  giftCardtImage: path('ic_card'),
  headphone: path('ic_headphone'),
  phone: path('ic_phone'),
  hm: path('ic_hm'),
  jumia: path('ic_jumia'),
  samsung: path('ic_samsung'),
  spar: path('ic_spar'),
  splash: path('ic_splash'),
  productService: path('ic_productService'),
  danush: path('ic_danush'),
  howItWorks: path('ic_howItWorks'),
  background01: path('ic_background01'),
  cust1440: path('1440'),
  cust1441: path('1441'),
  cust1442: path('1442'),
  cust1443: path('1443'),
  cust1444: path('1444'),
  cust1445: path('1445'),
  cust1446: path('1446'),
  cust1447: path('1447'),
  cust1448: path('1448'),
  cust1449: path('1449'),
  cust1441Bg: path('1441-big'),
  fileBg: path('fileBg'),
  inputBg: path('inputBg'),
  img97: path('img97'),
  printHome: path('printHome'),
  msignup: path('msignup'),
  userMap: path('userMap'),
  mRight: path('mRight'),
  faq: path('faq'),
  howToCard: path('howToCard'),
  sumsang: path('sumsang'),
  sparBG: path('sparBG'),
  jumiaBG: path('jumiaBG'),
  sureBusiness: path('sureBusiness'),
  profile: path('profile'),
  full97: path('97full'),
  profileBig: path('profileBig'),
  profileAvatar: path('profileAvatar'),
  united: path('united'),
  south: path('south'),
  india: path('india'),
  looking: path('looking'),
  home: path('home')
};

export default ImagesConfig;
